### ISSUE TITLE
Naming conflict: generate_input_spike_trains

### ISSUE THREAD

**Issue by skim0119** [GazzolaLab/MiV-Simulator#19]
There are three incidences of the name `generate_input_spike_trains`, and we should probably refactor them for the documentation. Also, it causes some conflicts [here](https://github.com/GazzolaLab/MiV-Simulator/blob/39bf5ae94eb72d088ab197c9f4b1e33ad780f434/src/miv_simulator/simulator/_generate_input_spike_trains.py#L406).

- File `src/scripts/generate_input_spike_trains.py` (executable)
- File `src/miv_simulator/simulator/_generate_input_spike_trains.py` (backend of executable)
  - Includes method `generate_input_spike_trains`
- File `src/miv_simulator/stimulus.py`
  - Includes method `generate_input_spike_trains`

**Comment by iraikov** [comment]
I don't really understand the issue here. The script provides user interface and I/O to the core generate_input_spike_trains routine. One could rename procedure generate_input_spike_trains in  src/miv_simulator/simulator/_generate_input_spike_trains.py to something else, but since it is in its own module, I do not see a problem being solved.

**Comment by frthjf** [comment]
If I understand correctly, the issue seems to be that `generate_input_spike_trains` [here](https://github.com/GazzolaLab/MiV-Simulator/blob/main/src/miv_simulator/simulator/_generate_input_spike_trains.py#L121) calls `generate_input_spike_trains` [here](https://github.com/GazzolaLab/MiV-Simulator/blob/main/src/miv_simulator/simulator/_generate_input_spike_trains.py#L406), causing a recursion - it is actually meant to call the imported `generate_input_spike_trains` [here](https://github.com/GazzolaLab/MiV-Simulator/blob/main/src/miv_simulator/simulator/_generate_input_spike_trains.py#L14). This is likely some issue that was introduced by the refactoring in #10.
